clean:
	/bin/rm -f *.ctxt *.class

main: BobbyFace.java Face.java FaceFrame.java FaceLabel.java HankFace.java HillFace.java HomerFace.java SimpsonFace.java
	javac BobbyFace.java Face.java FaceFrame.java FaceLabel.java HankFace.java HillFace.java HomerFace.java SimpsonFace.java